name: Test

on:
  pull_request:

env:
  NODE_ENV: ci
  PUBLIC_APP_ENV: ci
  PUBLIC_SENTRY_DSN:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/oh-my-gtd?schema=public
  REDIS_URL:
  JWT_SESSION_SECRET: ${{ secrets.JWT_SESSION_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
        redis-version: [7]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.3.0

      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test
